-- =========================================================================
-- ARCHIVO DE INICIALIZACIÓN Y REDISEÑO DE BASE DE DATOS (POSTGRESQL / SUPABASE)
-- PROYECTO: PIPE ICE CREAM - GESTIÓN DE INVENTARIO Y VENTAS
-- VERSIÓN: 3.0 (EDICIÓN ULTRA-OPTIMIZADA CON TRIGGERS, AUDITORÍA Y CALCULOS RPC)
-- =========================================================================

-- 1. LIMPIEZA TOTAL DE OBJETOS PREVIOS (Opcional, usar con precaución)
DROP TRIGGER IF EXISTS trg_audit_products ON products;
DROP TRIGGER IF EXISTS trg_audit_sales ON sales;
DROP TRIGGER IF EXISTS trg_audit_shop_config ON shop_config;
DROP TRIGGER IF EXISTS update_shop_config_updated_at ON shop_config;
DROP TRIGGER IF EXISTS update_products_updated_at ON products;
DROP TRIGGER IF EXISTS update_sales_updated_at ON sales;

DROP FUNCTION IF EXISTS process_audit_products();
DROP FUNCTION IF EXISTS process_audit_sales();
DROP FUNCTION IF EXISTS process_audit_shop_config();
DROP FUNCTION IF EXISTS update_updated_at_column();
DROP FUNCTION IF EXISTS deduct_stock_atomic(jsonb);
DROP FUNCTION IF EXISTS restore_stock_atomic(jsonb);
DROP FUNCTION IF EXISTS get_shop_kpis(text, text);
DROP FUNCTION IF EXISTS get_revenue_by_day(int);
DROP FUNCTION IF EXISTS reset_database();

DROP TABLE IF EXISTS sale_items CASCADE;
DROP TABLE IF EXISTS sales CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS shop_config CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;

-- 2. CREACIÓN DE TABLAS DE LA BASE DE DATOS

-- Tabla: Configuración global del establecimiento
CREATE TABLE shop_config (
    id TEXT PRIMARY KEY DEFAULT 'primary',
    tienda_nombre TEXT NOT NULL DEFAULT 'PIPE ICE CREAM',
    contrasena_admin TEXT NOT NULL DEFAULT 'PipeAdmin2026',
    whatsapp_telefono TEXT DEFAULT '573185074440',
    metodo_ordenar TEXT DEFAULT 'SABOR QUE REFRESCA TU DÍA',
    cuenta_numero TEXT DEFAULT '3184754263',
    cuenta_titular TEXT DEFAULT 'Alba Guaca',
    mostrar_reloj BOOLEAN DEFAULT false,
    mostrar_clima BOOLEAN DEFAULT false,
    sync_enabled BOOLEAN DEFAULT true,
    catalog_sort_order TEXT DEFAULT 'manual', -- 'manual', 'stock_desc', 'stock_asc', 'alphabetical'
    catalog_mode_enabled BOOLEAN DEFAULT false,
    catalog_mode_message TEXT DEFAULT 'SABORIFICACIÓN EN MANTENIMIENTO (SÓLO CATÁLOGO)\nSincronización pausada por el Administrador.',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla: Inventario de Sabores (Helados y paletas)
CREATE TABLE products (
    id TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    precio NUMERIC NOT NULL DEFAULT 0 CHECK (precio >= 0),
    costo NUMERIC NOT NULL DEFAULT 0 CHECK (costo >= 0),
    stock INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    imagen TEXT,
    reserved BOOLEAN DEFAULT false,
    orden_manual INT DEFAULT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla: Ventas y Pedidos (Historial y Control)
CREATE TABLE sales (
    id TEXT PRIMARY KEY, -- Formato 'ORD-XXXXXX' o UUID
    numero_orden SERIAL, -- Identificador de orden secuencial autogenerado
    fecha TEXT NOT NULL, -- Formato ISO: YYYY-MM-DD
    hora TEXT NOT NULL,  -- Formato militar: HH:MM
    cliente_nombre TEXT NOT NULL,
    cliente_telefono TEXT NOT NULL,
    total NUMERIC NOT NULL DEFAULT 0 CHECK (total >= 0),
    estado TEXT DEFAULT 'Pendiente', -- 'Pendiente', 'Aprobado', 'Rechazado', 'En espera', 'Pre-Aprobado', 'Entregado', 'Eliminada'
    payment_method TEXT DEFAULT 'efectivo', -- 'efectivo', 'transferencia'
    payment_with_bill NUMERIC DEFAULT NULL,
    payment_change NUMERIC DEFAULT NULL,
    payment_status TEXT DEFAULT 'Pendiente', -- 'Pendiente', 'Pagado', 'Anulado'
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla: Desglose o Detalle de Ventas (Productos vendidos)
CREATE TABLE sale_items (
    id BIGSERIAL PRIMARY KEY,
    sale_id TEXT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL,
    nombre TEXT NOT NULL,
    cantidad INT NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    precio_unitario NUMERIC NOT NULL DEFAULT 0 CHECK (precio_unitario >= 0),
    costo_unitario NUMERIC NOT NULL DEFAULT 0 CHECK (costo_unitario >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla: Auditoría completa del sistema (Trazabilidad estricta)
CREATE TABLE audit_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT NOT NULL,
    hora TEXT NOT NULL,
    accion TEXT NOT NULL,
    admin_responsable TEXT NOT NULL,
    entidad_afectada TEXT NOT NULL,
    entidad_id TEXT,
    valor_anterior JSONB,
    valor_nuevo JSONB,
    ip TEXT DEFAULT '127.0.0.1',
    navegador TEXT DEFAULT 'Desconocido',
    dispositivo TEXT DEFAULT 'Servidor',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ÍNDICES DE ALTO RENDIMIENTO (OPTIMIZACIÓN DE CONSULTAS)
CREATE INDEX idx_products_orden_manual ON products(orden_manual ASC NULLS LAST);
CREATE INDEX idx_products_stock ON products(stock);
CREATE INDEX idx_sales_fecha ON sales(fecha DESC);
CREATE INDEX idx_sales_estado ON sales(estado);
CREATE INDEX idx_sales_numero_orden ON sales(numero_orden DESC);
CREATE INDEX idx_sale_items_sale_id ON sale_items(sale_id);
CREATE INDEX idx_sale_items_product_id ON sale_items(product_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX idx_audit_logs_accion ON audit_logs(accion);

-- 4. SEGURIDAD Y POLÍTICAS (ROW LEVEL SECURITY - RLS)
ALTER TABLE shop_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Crear políticas universales (permitir operaciones completas para integración sin fricción)
CREATE POLICY "Public Full Access Shop Config" ON shop_config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access Products" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access Sales" ON sales FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access Sale Items" ON sale_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Full Access Audit Logs" ON audit_logs FOR ALL USING (true) WITH CHECK (true);

-- 5. FUNCIONES AUXILIARES Y TRIGGERS AUTOMÁTICOS

-- A. Función para actualización automática de la columna 'updated_at'
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_shop_config_updated_at BEFORE UPDATE ON shop_config FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_sales_updated_at BEFORE UPDATE ON sales FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();


-- B. Función de Auditoría de Productos
CREATE OR REPLACE FUNCTION process_audit_products()
RETURNS TRIGGER AS $$
DECLARE
    action_type TEXT;
    val_old JSONB := NULL;
    val_new JSONB := NULL;
    responsable TEXT := 'sistema_db';
BEGIN
    IF (TG_OP = 'DELETE') THEN 
        action_type := 'eliminacion_producto';
        val_old := to_jsonb(OLD);
    ELSIF (TG_OP = 'INSERT') THEN 
        action_type := 'creacion_producto';
        val_new := to_jsonb(NEW);
    ELSIF (TG_OP = 'UPDATE') THEN
        action_type := 'actualizacion_producto';
        val_old := to_jsonb(OLD);
        val_new := to_jsonb(NEW);
        IF (OLD.stock <> NEW.stock) THEN 
            action_type := 'cambio_stock';
        ELSIF (OLD.precio <> NEW.precio) THEN 
            action_type := 'cambio_precio';
        END IF;
    END IF;

    INSERT INTO audit_logs (fecha, hora, accion, admin_responsable, entidad_afectada, entidad_id, valor_anterior, valor_nuevo)
    VALUES (
        to_char(NOW() AT TIME ZONE 'America/Bogota', 'YYYY-MM-DD'), 
        to_char(NOW() AT TIME ZONE 'America/Bogota', 'HH24:MI'), 
        action_type, 
        responsable, 
        'products', 
        COALESCE(NEW.id, OLD.id), 
        val_old, 
        val_new
    );
    
    IF (TG_OP = 'DELETE') THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_audit_products AFTER INSERT OR UPDATE OR DELETE ON products FOR EACH ROW EXECUTE FUNCTION process_audit_products();


-- C. Función de Auditoría de Ventas y Sincronización de Pago
CREATE OR REPLACE FUNCTION process_audit_sales()
RETURNS TRIGGER AS $$
DECLARE
    action_type TEXT;
    val_old JSONB := NULL;
    val_new JSONB := NULL;
    responsable TEXT := 'sistema_ventas';
BEGIN
    IF (TG_OP = 'DELETE') THEN 
        action_type := 'eliminacion_venta';
        val_old := to_jsonb(OLD);
    ELSIF (TG_OP = 'INSERT') THEN 
        action_type := 'creacion_venta';
        val_new := to_jsonb(NEW);
    ELSIF (TG_OP = 'UPDATE') THEN
        action_type := 'actualizacion_venta';
        val_old := to_jsonb(OLD);
        val_new := to_jsonb(NEW);

        -- Lógica de negocio: Si se anula la venta, se anula el pago automáticamente
        IF (NEW.estado IN ('Rechazado', 'Eliminada')) THEN
            NEW.payment_status := 'Anulado';
        END IF;

        IF (OLD.estado <> NEW.estado) THEN 
            action_type := 'cambio_estado_venta';
        END IF;
    END IF;

    INSERT INTO audit_logs (fecha, hora, accion, admin_responsable, entidad_afectada, entidad_id, valor_anterior, valor_nuevo)
    VALUES (
        to_char(NOW() AT TIME ZONE 'America/Bogota', 'YYYY-MM-DD'), 
        to_char(NOW() AT TIME ZONE 'America/Bogota', 'HH24:MI'), 
        action_type, 
        responsable, 
        'sales', 
        COALESCE(NEW.id, OLD.id), 
        val_old, 
        val_new
    );
    
    IF (TG_OP = 'DELETE') THEN RETURN OLD; ELSE RETURN NEW; END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_audit_sales AFTER INSERT OR UPDATE OR DELETE ON sales FOR EACH ROW EXECUTE FUNCTION process_audit_sales();


-- D. Función de Auditoría de Configuración
CREATE OR REPLACE FUNCTION process_audit_shop_config()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_logs (fecha, hora, accion, admin_responsable, entidad_afectada, entidad_id, valor_anterior, valor_nuevo)
    VALUES (
        to_char(NOW() AT TIME ZONE 'America/Bogota', 'YYYY-MM-DD'), 
        to_char(NOW() AT TIME ZONE 'America/Bogota', 'HH24:MI'), 
        'actualizacion_ajustes', 
        'administrador', 
        'shop_config', 
        NEW.id, 
        to_jsonb(OLD), 
        to_jsonb(NEW)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_audit_shop_config AFTER UPDATE ON shop_config FOR EACH ROW EXECUTE FUNCTION process_audit_shop_config();


-- E. RPC: Descuento Atómico de Stock (Evita inconsistencias / condiciones de carrera)
CREATE OR REPLACE FUNCTION deduct_stock_atomic(items_to_deduct jsonb)
RETURNS jsonb AS $$
DECLARE
  item record;
  p_stock int;
  p_nombre text;
  result jsonb := '{"success": true}';
BEGIN
  -- 1. Verificar disponibilidad de stock para cada elemento antes de realizar cualquier cambio
  FOR item IN SELECT * FROM jsonb_to_recordset(items_to_deduct) AS (id text, cantidad int) LOOP
    SELECT stock, nombre INTO p_stock, p_nombre FROM products WHERE id = item.id FOR UPDATE;
    IF NOT FOUND THEN
      RETURN jsonb_build_object('success', false, 'error', 'Sabor de helado no encontrado: ' || item.id);
    END IF;
    IF p_stock < item.cantidad THEN
      RETURN jsonb_build_object('success', false, 'error', 'Stock insuficiente para ' || p_nombre, 'nombre', p_nombre, 'stock', p_stock, 'requested', item.cantidad);
    END IF;
  END LOOP;

  -- 2. Restar stock a los productos correspondientes
  FOR item IN SELECT * FROM jsonb_to_recordset(items_to_deduct) AS (id text, cantidad int) LOOP
    UPDATE products SET stock = stock - item.cantidad, updated_at = NOW() WHERE id = item.id;
  END LOOP;

  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- F. RPC: Restauración Atómica de Stock (Devolución por cancelación o rechazo de ventas)
CREATE OR REPLACE FUNCTION restore_stock_atomic(items_to_restore jsonb)
RETURNS jsonb AS $$
DECLARE
  item record;
  result jsonb := '{"success": true}';
BEGIN
  FOR item IN SELECT * FROM jsonb_to_recordset(items_to_restore) AS (id text, cantidad int) LOOP
    UPDATE products SET stock = stock + item.cantidad, updated_at = NOW() WHERE id = item.id;
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- G. RPC: Obtener Estadísticas y KPIs Globales Rápidos (Mejora drásticamente el rendimiento de la App)
CREATE OR REPLACE FUNCTION get_shop_kpis(p_fecha_inicio text DEFAULT NULL, p_fecha_fin text DEFAULT NULL)
RETURNS jsonb AS $$
DECLARE
  v_ventas_totales numeric := 0;
  v_costos_totales numeric := 0;
  v_ganancia_neta numeric := 0;
  v_num_pedidos int := 0;
  v_ticket_promedio numeric := 0;
  v_metodo_favorito text := 'Ninguno';
BEGIN
  -- Filtrar según las fechas si se suministran, de lo contrario tomar el histórico total
  SELECT 
    COALESCE(SUM(total), 0),
    COUNT(*),
    COALESCE(AVG(total), 0)
  INTO v_ventas_totales, v_num_pedidos, v_ticket_promedio
  FROM sales
  WHERE (p_fecha_inicio IS NULL OR fecha >= p_fecha_inicio)
    AND (p_fecha_fin IS NULL OR fecha <= p_fecha_fin)
    AND estado NOT IN ('Rechazado', 'Eliminada');

  -- Calcular costos totales recorriendo los items de ventas válidas
  SELECT COALESCE(SUM(i.cantidad * i.costo_unitario), 0)
  INTO v_costos_totales
  FROM sale_items i
  JOIN sales s ON i.sale_id = s.id
  WHERE (p_fecha_inicio IS NULL OR s.fecha >= p_fecha_inicio)
    AND (p_fecha_fin IS NULL OR s.fecha <= p_fecha_fin)
    AND s.estado NOT IN ('Rechazado', 'Eliminada');

  v_ganancia_neta := v_ventas_totales - v_costos_totales;

  -- Método de pago más utilizado
  SELECT payment_method
  INTO v_metodo_favorito
  FROM sales
  WHERE (p_fecha_inicio IS NULL OR fecha >= p_fecha_inicio)
    AND (p_fecha_fin IS NULL OR fecha <= p_fecha_fin)
    AND estado NOT IN ('Rechazado', 'Eliminada')
  GROUP BY payment_method
  ORDER BY COUNT(*) DESC
  LIMIT 1;

  RETURN jsonb_build_object(
    'ventas_totales', v_ventas_totales,
    'costos_totales', v_costos_totales,
    'ganancia_neta', v_ganancia_neta,
    'num_pedidos', v_num_pedidos,
    'ticket_promedio', ROUND(v_ticket_promedio, 2),
    'metodo_preferido', COALESCE(v_metodo_favorito, 'N/A')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- H. RPC: Agrupación de Ingresos de los Últimos Días (Gráfica de Tendencias en la Base de Datos)
CREATE OR REPLACE FUNCTION get_revenue_by_day(p_limit int DEFAULT 30)
RETURNS TABLE (fecha_dia TEXT, total_ventas NUMERIC, total_pedidos BIGINT) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    fecha AS fecha_dia,
    COALESCE(SUM(total), 0) AS total_ventas,
    COUNT(*) AS total_pedidos
  FROM sales
  WHERE estado NOT IN ('Rechazado', 'Eliminada')
  GROUP BY fecha
  ORDER BY fecha DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- I. Función para Reiniciar Tablas (Mantenimiento del administrador)
CREATE OR REPLACE FUNCTION reset_database()
RETURNS text AS $$
BEGIN
    DELETE FROM sale_items;
    DELETE FROM sales;
    DELETE FROM products;
    DELETE FROM audit_logs;
    DELETE FROM shop_config;
    RETURN 'Base de datos de Pipe Ice Cream reiniciada con éxito.';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Función para reiniciar únicamente las ventas y reiniciar los contadores e IDs secuenciales (TRUNCATE ... RESTART IDENTITY CASCADE)
CREATE OR REPLACE FUNCTION reset_sales_and_sequences()
RETURNS text AS $$
BEGIN
    TRUNCATE TABLE sale_items RESTART IDENTITY CASCADE;
    TRUNCATE TABLE sales RESTART IDENTITY CASCADE;
    
    -- Reiniciar secuencias explícitamente
    -- BIGSERIAL crea una secuencia por defecto. Buscamos el nombre de la secuencia asociada a 'id' en 'sale_items'
    EXECUTE 'ALTER SEQUENCE IF EXISTS ' || pg_get_serial_sequence('public.sale_items', 'id') || ' RESTART WITH 1';
    
    -- Reiniciar secuencia de orden secuencial
    ALTER SEQUENCE IF EXISTS sales_numero_orden_seq RESTART WITH 1;
    
    RETURN 'Ventas y detalles eliminados con éxito, secuencias de IDs reiniciadas.';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 6. INSERCIÓN DE VALORES POR DEFECTO PARA PIPE ICE CREAM

-- Configuración Inicial
INSERT INTO shop_config (id, tienda_nombre, contrasena_admin, whatsapp_telefono, metodo_ordenar, cuenta_numero, cuenta_titular, mostrar_reloj, mostrar_clima)
VALUES (
    'primary', 
    'PIPE ICE CREAM', 
    'PipeAdmin2026', 
    '573185074440', 
    'SABOR QUE REFRESCA TU DIA', 
    '3184754263', 
    'Alba Guaca', 
    false, 
    false
)
ON CONFLICT (id) DO NOTHING;

-- Sabores Reales del Catálogo de Helados (Sincronizado con db.json original)
INSERT INTO products (id, nombre, precio, costo, stock, imagen, reserved, orden_manual)
VALUES 
('PROD-1', 'Queso', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1W9ZtSzMXJY7lC93En7h9z9F1NC41-IX3', false, 1),
('PROD-2', 'Coco', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1NYj2eM6mWBOMwsFh8kluqgkLICI3AjHd', false, 2),
('PROD-3', 'Salpicon', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1GiLJ4mJQlM_PLTMl9nM9KIQwBqQ_DfLw', false, 3),
('PROD-4', 'ChocoVainilla', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/18lJnx9HSQ8sW7pWQ8nBPZJNtfxxW-4OM', false, 4),
('PROD-5', 'Ron & Pasas', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1xp3eILHmEgilmBCxwacyKm36oiGiPBtL', false, 5),
('PROD-6', 'Mani', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1HPUpv6N2cRoK5gWa1u3BEGGjddhSP_xx', false, 6),
('PROD-7', 'Chicle', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1gz2TtlHTWbcXYQ82sXd8qMuYiWXocJLJ', false, 7),
('PROD-8', 'Paleta Mango Biche', 2200, 920, 0, 'https://lh3.googleusercontent.com/d/171saTSIh_oNyGc-ljUwQkML7URKro_0n', false, 8),
('PROD-9', 'Fresa', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1LKGimUBAp2H6gy6fzS96gBxqJoBofAsP', false, 9),
('PROD-10', 'Guanabana', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1T4RKTW92Mnjo3MM8OD8AXQQA0QymnFWn', false, 10),
('PROD-11', 'Mora', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1Nl0mMpEsOY5M2uEZwMTF0uFnQkB_QO2t', false, 11),
('PROD-12', 'Piña', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1LrfXAqRlp_nD26djCB8SamOv1pTfGWrJ', false, 12),
('PROD-13', 'Maracuya', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1vqhnmyrG_gPZSzEjDVzJ1hiBbqVQmn23', false, 13),
('PROD-14', 'Frutos Rojos', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1NDOp3XZ2LQncY1Npw-xES5Cmhd11gXrg', false, 14),
('PROD-15', 'Lulo', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/12ooVCX2Ej4gBx3ktn546PeJ5YKIX-uaV', false, 15),
('PROD-16', 'Arequipe', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/18Bcgx26CEaJZNM_L8ZPpAxVKMXZ_vb_V', false, 16),
('PROD-17', 'Turron', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/11OKU8C8gv7IWsYJ6pPvCRcQ6FnfWsv1x', false, 17),
('PROD-18', 'Tres Leches', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1Ybw65NThzJzVT0AQECufm9FUwQhonMmZ', false, 18),
('PROD-19', 'Mango Tommy', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1dyn3Z_AHnUF0RL-Lrs-ydo2qZOLj64hl', false, 19),
('PROD-20', 'Naranja - Piña', 2200, 1140, 0, 'https://lh3.googleusercontent.com/d/1H-c7AxH01S7o7JHlIKIhPiDr-ZOX4W41', false, 20)
ON CONFLICT (id) DO NOTHING;

-- Registro de auditoría del sistema de inicialización exitosa
INSERT INTO audit_logs (fecha, hora, accion, admin_responsable, entidad_afectada, entidad_id, valor_nuevo)
VALUES (
    to_char(NOW() AT TIME ZONE 'America/Bogota', 'YYYY-MM-DD'), 
    to_char(NOW() AT TIME ZONE 'America/Bogota', 'HH24:MI'), 
    'inicializacion_sistema', 
    'sistema_db', 
    'schema', 
    'version-3.0', 
    '{"message": "Base de datos inicializada de forma limpia con configuraciones de la tienda"}'
);

-- Fin del Script de Inicialización